
import type { Metadata } from "next";
import { Maven_Pro } from "next/font/google";
import "./globals.css";
import "@solana/wallet-adapter-react-ui/styles.css";
import Wallet from "./providers/wallet-provider";
import { AuthProvider } from "@/context/AuthContext";
import { Navigation } from "@/components/ui/Navigation";

const mavenPro = Maven_Pro({
  subsets: ["latin"],
  variable: "--font-sans", // Use --font-sans for shadcn/ui
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={mavenPro.variable}>
      <body className="antialiased">
        <Wallet>
          <AuthProvider>
            <Navigation />
            {children}
          </AuthProvider>
        </Wallet>
      </body>
    </html>
  );
}
